[workspace]
authors = ["AbderrahimAl <abderrahimalakouche@gmail.com>"]
channels = ["knime/label/githubTest", "knime", "conda-forge"]
name = "py39_bert_cpu"
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
py4j = "*"
nomkl = "*"
pandas = "*"
numpy = "*"
pyarrow = "<8.0"
tokenizers = "0.12.1.*"      # Needed by spacy
spacy-pkuseg = "<0.1.0.*"     # Needed by chinese models
spacy = "3.5.3.*"
pytorch = "1.12.1.*"
spacy-transformers = "1.1.8.*"
pymorphy2 = "*"
pymorphy3-dicts-uk = "*"
sudachipy = "*"
sudachidict-core = "*"
pip = "*"


[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = "5.6.*"

[feature.debug.dependencies]
debugpy = "*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "build-python-extension . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}
debug = {features = ["debug"]}