[workspace]
authors = ["AbderrahimAl <abderrahimalakouche@gmail.com>"]
channels = ["knime/label/githubTest", "knime", "conda-forge"]
name = "py39-spacy-cpu"
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.1.0"


# Shared dependencies across all platforms
[dependencies]
python = "3.9"
py4j = "*"
pandas = "*"
numpy = "*"
pyarrow = "<8.0"
tokenizers = "0.12.1"
spacy-pkuseg = "<0.1.0"

# -------------------------------
# Win64 and Linux64: pip-based torch + spacy
# -------------------------------
[target.win-64.pip-dependencies]
torch = "==1.12.1"
spacy = "==3.5.3"
spacy-transformers = "==1.1.7"
pymorphy2 = "*"
pymorphy3 = "*"
pymorphy3-dicts-uk = "*"
sudachipy = "*"
sudachidict-core = "*"

[target.linux-64.pip-dependencies]
torch = "==1.12.1"
spacy = "==3.5.3"
spacy-transformers = "==1.1.7"
pymorphy2 = "*"
pymorphy3 = "*"
pymorphy3-dicts-uk = "*"
sudachipy = "*"
sudachidict-core = "*"

# -------------------------------
# OSX: conda-based spacy + torch + spacy-transformers
# -------------------------------
[target.osx-64.dependencies]
spacy = "3.5.3"
pytorch = "1.12.1"
spacy-transformers = "1.1.8"

[target.osx-64.pip-dependencies]
pymorphy2 = "*"
pymorphy3 = "*"
pymorphy3-dicts-uk = "*"
sudachipy = "*"
sudachidict-core = "*"


[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = "5.6.*"

[feature.debug.dependencies]
debugpy = "*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "build-python-extension . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}
debug = {features = ["debug"]}